[project]
name = "judo-site"
version = "0.1.0"
description = "Sitio web minimalista para amantes del judo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "zensical>=0.0.23",
]
